### ISSUE TITLE
More than 100 products?

### ISSUE THREAD

**Issue by darrylmorley** [scottyzen/Gridsome-WooCommerce#1]
Hi,
I've followed your example here with a project I'm working on. I'm wondering if you've had any joy pulling more than 100 products from Woocommerce with this approach?

**Comment by scottyzen** [comment]
I updated the gridsome.server.js file if you would like to take a look. It's a quick workaround for now. I have it set to add 500 products. Just change the amount of time for the loop to run, every iteration will add 100 products. If you have 1050 products, set it to loop 11 times.

**Comment by darrylmorley** [comment]
Awesome, I was going to look at that this morning after a bit of reading last night. Thanks for this!
